version: 0.1
phases:
  pre_build:
    commands:
      - node -v
      - npm -v
      - echo Installing dependencies...
#      - npm config set "@fortawesome:registry" https://npm.fontawesome.com/
#      - npm config set "//npm.fontawesome.com/:_authToken" 6732C8AA-0A3D-4BC0-8A35-94068BDBA900
#      - npm install --loglevel=error
      - npm i
  build:
    commands:
      - echo Building...
      - npm run-script build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: ./build
cache:
  paths:
    - 'node_modules/**/*'
