version: 0.1
phases:
  pre_build:
    commands:
      - node -v
      - npm -v
      - echo Installing dependencies...
      - npm install --force --loglevel=error
  build:
    commands:
      - echo Building...
      - npm run-script build
#      - react-scripts build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: ./build
cache:
  paths:
    - 'node_modules/**/*'
