version: 0.1
phases:
  pre_build:
    commands:
      - node -v
      - npm -v
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building...
      - npm run-script build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: ./build
